import { useState, useEffect, useCallback } from 'react'
import StatusTab from './components/StatusTab'
import NodesTab from './components/NodesTab'
import AccountTab from './components/AccountTab'

// Wails runtime bindings — generated by `wails dev` / `wails build`
// @ts-ignore
import { GetStatus, ToggleVPN, GetAccount, StartLogin, Logout, OpenConsole, GetPortalHost, IsConfigured, WindowStartDrag } from '../wailsjs/go/main/App'
// @ts-ignore
import { EventsOn } from '../wailsjs/runtime/runtime'

export type StatusData = {
  configured: boolean   // true once the embedded VPN service has started
  running: boolean
  device_running: boolean
  tun_mode: boolean
  tun_name: string
  exit_node: boolean
  ips: string[]
  pubkey: string
  rx_bytes: number
  tx_bytes: number
  peers: PeerInfo[]
}

export type PeerInfo = {
  public_key: string
  endpoint: string
  allowed_ips: string
  rx_bytes: number
  tx_bytes: number
  last_handshake: string
  is_relay: boolean
  is_exit_node: boolean
  latency_ms: number
}

export type AccountInfo = {
  logged_in: boolean
  token: string
  display_name: string
  email: string
  avatar_url: string
}

type Tab = 'status' | 'nodes' | 'account'

export default function App() {
  const [tab, setTab] = useState<Tab>('status')
  const [status, setStatus] = useState<StatusData | null>(null)
  const [account, setAccount] = useState<AccountInfo | null>(null)
  const [portalHost, setPortalHost] = useState('console.wantastic.app')
  const [loading, setLoading] = useState(true)
  const [configuring, setConfiguring] = useState(false) // true while registering device

  const refreshStatus = useCallback(async () => {
    try {
      const s: StatusData = await GetStatus()
      setStatus(s)
      // If service just started and there's no config yet, guide user to Account tab
      if (!s.configured && tab === 'status') {
        setTab('account')
      }
    } catch {
      // Unexpected error — keep previous state
    } finally {
      setLoading(false)
    }
  }, [tab])

  const refreshAccount = useCallback(async () => {
    try {
      const a: AccountInfo = await GetAccount()
      setAccount(a)
    } catch {}
  }, [])

  useEffect(() => {
    refreshStatus()
    refreshAccount()
    GetPortalHost().then(setPortalHost).catch(() => {})

    // Listen for background status pushes from Go
    EventsOn('status:update', (s: StatusData) => {
      setStatus(s)
    })
    EventsOn('auth:complete', (a: AccountInfo) => {
      setAccount(a)
    })
    // Fired when Go is downloading / decrypting WireGuard config from backend
    EventsOn('service:configuring', () => {
      setConfiguring(true)
    })
    // Fired once the embedded VPN service has started successfully
    EventsOn('service:ready', () => {
      setConfiguring(false)
      refreshStatus()
      refreshAccount()
      setTab('status')
    })

    const interval = setInterval(refreshStatus, 6000)
    return () => clearInterval(interval)
  }, [refreshStatus])

  const handleToggleVPN = async () => {
    try { await ToggleVPN() } catch {}
    await refreshStatus()
  }

  const connected = status?.running && status?.device_running
  const peerCount = status?.peers?.length ?? 0
  const serviceConfigured = status?.configured ?? false

  return (
    <div className="app">
      {/* Custom titlebar / drag zone */}
      <div className="titlebar" onMouseDown={() => WindowStartDrag()}>
        <div className="titlebar-logo">
          <img src="/logo.png" width={20} height={20} alt="Wantastic" />
          <span className="titlebar-name">Wantastic</span>
        </div>
        <div className="titlebar-status">
          <span className={`status-dot ${connected ? 'connected' : 'disconnected'}`} />
          <span className="status-label">{connected ? 'Connected' : 'Disconnected'}</span>
        </div>
        <div className="titlebar-spacer" />
      </div>

      {/* Hero stats strip */}
      <div className="hero-strip" onClick={handleToggleVPN}>
        <div className={`hero-glow ${connected ? 'glow-green' : 'glow-dim'}`} />
        <div className="hero-content">
          <div className="hero-left">
            <div className={`vpn-toggle-btn ${connected ? 'on' : 'off'}`}>
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
                <circle cx="12" cy="12" r="9" strokeWidth="2" stroke={connected ? '#00d97e' : '#666'} />
                <path d="M12 7v5l3 3" strokeWidth="2" stroke={connected ? '#00d97e' : '#666'} strokeLinecap="round"/>
              </svg>
            </div>
            <div>
              <div className="hero-state">{connected ? 'Protected' : 'Not Protected'}</div>
              <div className="hero-ips">{status?.ips?.[0] ?? '—'}</div>
            </div>
          </div>
          <div className="hero-right">
            <div className="hero-stat">
              <span className="stat-icon">↓</span>
              <span>{formatBytes(status?.rx_bytes ?? 0)}</span>
            </div>
            <div className="hero-stat">
              <span className="stat-icon">↑</span>
              <span>{formatBytes(status?.tx_bytes ?? 0)}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Tab bar */}
      <div className="tabbar">
        {(['status', 'nodes', 'account'] as Tab[]).map(t => (
          <button
            key={t}
            className={`tab-btn ${tab === t ? 'active' : ''}`}
            onClick={() => setTab(t)}
          >
            {t === 'status' && <TabIcon name="status" active={tab === 'status'} />}
            {t === 'nodes' && (
              <span className="tab-badge-wrap">
                <TabIcon name="nodes" active={tab === 'nodes'} />
                {peerCount > 0 && <span className="tab-badge">{peerCount}</span>}
              </span>
            )}
            {t === 'account' && <TabIcon name="account" active={tab === 'account'} />}
            <span className="tab-label">{t.charAt(0).toUpperCase() + t.slice(1)}</span>
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div className="tab-content">
        {loading ? (
          <div className="loading-state">
            <div className="spinner" />
            <span>Starting Wantastic…</span>
          </div>
        ) : !serviceConfigured ? (
          // No config on disk yet — redirect to Account tab so the user can sign in
          // and download their VPN configuration.
          <AccountTab
            account={account}
            portalHost={portalHost}
            configuring={configuring}
            onLogin={async () => { await StartLogin(); await refreshAccount() }}
            onLogout={async () => { await Logout(); setAccount(null) }}
            onOpenConsole={() => OpenConsole()}
          />
        ) : (
          <>
            {tab === 'status' && <StatusTab status={status} onToggle={handleToggleVPN} />}
            {tab === 'nodes' && <NodesTab status={status} />}
            {tab === 'account' && (
              <AccountTab
                account={account}
                portalHost={portalHost}
                configuring={configuring}
                onLogin={async () => { await StartLogin(); await refreshAccount() }}
                onLogout={async () => { await Logout(); setAccount(null) }}
                onOpenConsole={() => OpenConsole()}
              />
            )}
          </>
        )}
      </div>
    </div>
  )
}

function TabIcon({ name, active }: { name: string; active: boolean }) {
  const c = active ? '#3d8ef0' : '#888'
  if (name === 'status') return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
      <path d="M3 12h4l3 7 4-14 3 7h4" stroke={c} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
  if (name === 'nodes') return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
      <circle cx="12" cy="5" r="2.5" stroke={c} strokeWidth="1.8"/>
      <circle cx="5" cy="19" r="2.5" stroke={c} strokeWidth="1.8"/>
      <circle cx="19" cy="19" r="2.5" stroke={c} strokeWidth="1.8"/>
      <path d="M12 7.5v4M12 11.5l-5.5 5M12 11.5l5.5 5" stroke={c} strokeWidth="1.8" strokeLinecap="round"/>
    </svg>
  )
  if (name === 'account') return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
      <circle cx="12" cy="8" r="4" stroke={c} strokeWidth="1.8"/>
      <path d="M4 20c0-3.3 3.6-6 8-6s8 2.7 8 6" stroke={c} strokeWidth="1.8" strokeLinecap="round"/>
    </svg>
  )
  return null
}

function formatBytes(b: number): string {
  if (b >= 1e9) return (b / 1e9).toFixed(2) + ' GB'
  if (b >= 1e6) return (b / 1e6).toFixed(1) + ' MB'
  if (b >= 1e3) return (b / 1e3).toFixed(0) + ' KB'
  return b + ' B'
}
