package wusp

// mesh_telemetry.go models Wantastic mesh telemetry as a vendor extension to
// the TR-181 Device root. The WUSP_ prefix mirrors the vendor-prefixed style
// used by CPE vendors for non-standard parameters while keeping the object tree
// separate from Device.WUSP.*, which is reserved for the transport itself.

const WUSPMeshTelemetryPrefix = "Device.WUSP_MeshTelemetry."

// WUSPMeshTelemetryObjects describes the custom mesh telemetry object surface.
var WUSPMeshTelemetryObjects = []Object{
	{
		Path:         WUSPMeshTelemetryPrefix,
		SinceVersion: "1.0",
		Description:  "Wantastic mesh telemetry extension for topology, link quality, and routing health.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "Node.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "Per-node mesh telemetry observed by the Wantastic agent.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "Link.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "Per-link mesh telemetry between Wantastic mesh nodes.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "Route.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "Per-route mesh telemetry and next-hop health.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "Protocol.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "Mesh protocol discovered or exposed by the Wantastic agent.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "OpenWrt IEEE 802.11s mesh interface configuration and runtime state.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "Peer-link telemetry from an IEEE 802.11s mesh interface.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "OpenWrt batman-adv mesh interface configuration and runtime state.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "batman-adv originator table row.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "batman-adv neighbor table row.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "batman-adv local or global translation-table row.",
	},
	{
		Path:          WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.",
		MultiInstance: true,
		SinceVersion:  "1.0",
		Description:   "batman-adv gateway announcement row.",
	},
}

var WUSPMeshTelemetryRootParams = []Param{
	{
		Path:         WUSPMeshTelemetryPrefix + "Enable",
		Type:         TypeBoolean,
		Access:       ReadWrite,
		SinceVersion: "1.0",
		Description:  "Enables publication of Wantastic mesh telemetry over WUSP.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Status",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Current mesh telemetry collection status.",
		Limits:       Limits{Enums: []string{"Disabled", "Collecting", "Partial", "Error"}},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "CollectionInterval",
		Type:         TypeUnsignedInt,
		Access:       ReadWrite,
		SinceVersion: "1.0",
		Description:  "Mesh telemetry collection interval in seconds.",
		Limits:       Limits{Min: iptr(1), Max: iptr(86400)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "LastSampleTime",
		Type:         TypeDateTime,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Timestamp of the most recent mesh telemetry sample.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "NodeNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.Node.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "LinkNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.Link.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "RouteNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.Route.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "ProtocolNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.Protocol.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "IEEE80211sNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.IEEE80211s.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "BATMANAdvNumberOfEntries",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of entries in Device.WUSP_MeshTelemetry.BATMANAdv.{i}.",
		Limits:       Limits{Min: iptr(0)},
	},
}

var WUSPMeshTelemetryNodeParams = []Param{
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.Alias",
		Type:         TypeAlias,
		Access:       ReadWrite,
		SinceVersion: "1.0",
		Description:  "USP non-functional unique key for this mesh node telemetry row.",
		Limits:       Limits{MinLength: 1, MaxLength: 64},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.NodeID",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Stable Wantastic mesh node identifier.",
		Limits:       Limits{MaxLength: 128},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.MACAddress",
		Type:         TypeMACAddress,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Primary mesh, IEEE 1905 AL, or backhaul MAC address for this node when known.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.PeerReference",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the peer represented by this telemetry node.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.ParentNode",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the parent mesh node that provides this node's upstream/backhaul path.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.ParentMACAddress",
		Type:         TypeMACAddress,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "MAC address of the parent mesh node when the source topology reports parent identity by MAC.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.Role",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Mesh role advertised by this node.",
		Limits:       Limits{Enums: []string{"Controller", "Relay", "Edge", "Client", "Unknown"}},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.Status",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Current reachability status of this mesh node.",
		Limits:       Limits{Enums: []string{"Online", "Degraded", "Offline", "Unknown"}},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.Hostname",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Hostname reported for this mesh node when available.",
		Limits:       Limits{MaxLength: 256},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.PublicKey",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "WireGuard public key associated with this mesh node.",
		Limits:       Limits{MaxLength: 128},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.Address",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Primary overlay address associated with this mesh node.",
		Limits:       Limits{MaxLength: 128},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.HopCount",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of parent/backhaul hops from the controller or topology root to this node.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.LastSeen",
		Type:         TypeDateTime,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Timestamp when this mesh node was last observed.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Node.{i}.NeighborCount",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Number of directly observed mesh neighbors for this node.",
		Limits:       Limits{Min: iptr(0)},
	},
}

var WUSPMeshTelemetryLinkParams = []Param{
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.Alias",
		Type:         TypeAlias,
		Access:       ReadWrite,
		SinceVersion: "1.0",
		Description:  "USP non-functional unique key for this mesh link telemetry row.",
		Limits:       Limits{MinLength: 1, MaxLength: 64},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.SourceNode",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the source Device.WUSP_MeshTelemetry.Node.{i}. row.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.TargetNode",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the target Device.WUSP_MeshTelemetry.Node.{i}. row.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.SourceMACAddress",
		Type:         TypeMACAddress,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "MAC address of the source node for this topology link when known.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.TargetMACAddress",
		Type:         TypeMACAddress,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "MAC address of the target node for this topology link when known.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.LinkType",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Physical medium observed for this mesh link.",
		Limits:       Limits{Enums: []string{"Wi-Fi", "Ethernet"}},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.InterfaceName",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Local interface which supplied the physical link evidence.",
		Limits:       Limits{MaxLength: 64},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.DiscoveryProtocol",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Protocol or kernel source which supplied the physical link evidence.",
		Limits:       Limits{MaxLength: 64},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.Status",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Current status of this mesh link.",
		Limits:       Limits{Enums: []string{"Up", "Degraded", "Down", "Unknown"}},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.Metric",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Controller-computed mesh path metric for this link. Lower values are preferred.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.LatencyAverage",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Average one-way or round-trip link latency in milliseconds, depending on probe source.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.JitterAverage",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Average observed jitter in milliseconds for this mesh link.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.PacketLoss",
		Type:         TypeDecimal,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Observed packet loss percentage for this mesh link.",
		Limits:       Limits{MinF: fptr(0), MaxF: fptr(100)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.ThroughputEstimate",
		Type:         TypeUnsignedLong,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Estimated usable throughput for this mesh link in bits per second.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.SignalQuality",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Normalized link quality score from 0 to 100.",
		Limits:       Limits{Min: iptr(0), Max: iptr(100)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Link.{i}.LastChange",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Seconds since this mesh link status last changed.",
		Limits:       Limits{Min: iptr(0)},
	},
}

var WUSPMeshTelemetryRouteParams = []Param{
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.Alias",
		Type:         TypeAlias,
		Access:       ReadWrite,
		SinceVersion: "1.0",
		Description:  "USP non-functional unique key for this mesh route telemetry row.",
		Limits:       Limits{MinLength: 1, MaxLength: 64},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.DestinationPrefix",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Destination prefix reached through this mesh route.",
		Limits:       Limits{MaxLength: 128},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.NextHopNode",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the next-hop mesh node for this route.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.Interface",
		Type:         TypePathRef,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Path reference to the interface used for this route.",
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.Metric",
		Type:         TypeUnsignedInt,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Controller-computed route metric. Lower values are preferred.",
		Limits:       Limits{Min: iptr(0)},
	},
	{
		Path:         WUSPMeshTelemetryPrefix + "Route.{i}.Status",
		Type:         TypeString,
		Access:       ReadOnly,
		SinceVersion: "1.0",
		Description:  "Current route health.",
		Limits:       Limits{Enums: []string{"Reachable", "Degraded", "Unreachable", "Unknown"}},
	},
}

var WUSPMeshTelemetryProtocolParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Alias", Type: TypeAlias, Access: ReadWrite, SinceVersion: "1.0", Description: "USP non-functional unique key for this mesh protocol row.", Limits: Limits{MinLength: 1, MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Name", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Mesh protocol name advertised by the agent.", Limits: Limits{Enums: []string{"EasyMesh", "MultiAP", "IEEE80211s", "BATMANAdv", "OLSR", "Babel", "OpenMesh", "Unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Implementation", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Implementation or daemon exposing this protocol.", Limits: Limits{Enums: []string{"OpenWrt", "hostapd", "wpa_supplicant", "mesh11sd", "batman-adv", "olsrd", "babeld", "Vendor", "Unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Version", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Protocol or implementation version when known.", Limits: Limits{MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Status", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Protocol runtime status.", Limits: Limits{Enums: []string{"Enabled", "Disabled", "Running", "Degraded", "Error", "Unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.Writable", Type: TypeBoolean, Access: ReadOnly, SinceVersion: "1.0", Description: "Whether the agent can apply writable parameters for this protocol on this device."},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.StandardMultiAPReference", Type: TypePathRef, Access: ReadOnly, SinceVersion: "1.0", Description: "Reference into Device.WiFi.MultiAP.* when this protocol is EasyMesh/MultiAP."},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.PrimaryObject", Type: TypePathRef, Access: ReadOnly, SinceVersion: "1.0", Description: "Reference to the primary protocol-specific object row."},
	{Path: WUSPMeshTelemetryPrefix + "Protocol.{i}.LastChange", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Seconds since this protocol status last changed.", Limits: Limits{Min: iptr(0)}},
}

var WUSPMeshTelemetryIEEE80211sParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Alias", Type: TypeAlias, Access: ReadWrite, SinceVersion: "1.0", Description: "USP non-functional unique key for this IEEE 802.11s row.", Limits: Limits{MinLength: 1, MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Enable", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "Enables the OpenWrt IEEE 802.11s mesh interface when the agent supports configuration writes."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Status", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "IEEE 802.11s interface runtime status.", Limits: Limits{Enums: []string{"Up", "Down", "Dormant", "LowerLayerDown", "Error", "Unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.ProtocolReference", Type: TypePathRef, Access: ReadOnly, SinceVersion: "1.0", Description: "Reference to Device.WUSP_MeshTelemetry.Protocol.{i}. for IEEE80211s."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.RadioReference", Type: TypePathRef, Access: ReadOnly, SinceVersion: "1.0", Description: "Reference to the Wi-Fi radio backing this mesh interface."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.InterfaceName", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Linux interface name for the mesh point.", Limits: Limits{MaxLength: 32}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Network", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt network section bridged to this mesh interface.", Limits: Limits{MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshID", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "IEEE 802.11s Mesh ID used by nodes joining this mesh.", Limits: Limits{MaxLength: 32}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Encryption", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt wireless encryption mode for the mesh interface.", Limits: Limits{Enums: []string{"none", "sae", "psk2", "psk-mixed", "unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Key", Type: TypeString, Access: WriteOnly, SinceVersion: "1.0", Description: "Write-only mesh passphrase or key material.", Limits: Limits{MinLength: 8, MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Channel", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "Configured mesh radio channel.", Limits: Limits{Min: iptr(1), Max: iptr(233)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshForwarding", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_fwding setting."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshNoLearn", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_nolearn setting."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshRSSIThreshold", Type: TypeInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_rssi_threshold setting in dBm.", Limits: Limits{Min: iptr(-255), Max: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshMaxPeerLinks", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_max_peer_links setting.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshMaxRetries", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_max_retries setting.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshHWMPRootMode", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_hwmp_rootmode setting.", Limits: Limits{Min: iptr(0), Max: iptr(4)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshGateAnnouncements", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_gate_announcements setting."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshConnectedToGate", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_connected_to_gate setting."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshConnectedToAS", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_connected_to_as setting."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.MeshTTL", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt mesh_ttl setting.", Limits: Limits{Min: iptr(1), Max: iptr(255)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.PeerNumberOfEntries", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Number of IEEE 802.11s peer-link rows.", Limits: Limits{Min: iptr(0)}},
}

var WUSPMeshTelemetryIEEE80211sPeerParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.MACAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Peer mesh station MAC address."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.Hostname", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Peer hostname when resolved by the agent.", Limits: Limits{MaxLength: 256}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.LinkState", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "802.11s peer-link state.", Limits: Limits{Enums: []string{"LISTEN", "OPN-SNT", "OPN-RCVD", "CNF-RCVD", "ESTAB", "HOLDING", "BLOCKED", "UNKNOWN"}}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.LocalLinkID", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Local mesh peer-link identifier.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.PeerLinkID", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Remote mesh peer-link identifier.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.SignalStrength", Type: TypeInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Peer signal strength in dBm.", Limits: Limits{Min: iptr(-255), Max: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.InactiveTime", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Milliseconds since the peer was last active.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.RXBytes", Type: TypeStatsCounter, Access: ReadOnly, SinceVersion: "1.0", Description: "Bytes received from this peer."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.TXBytes", Type: TypeStatsCounter, Access: ReadOnly, SinceVersion: "1.0", Description: "Bytes transmitted to this peer."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.RXPackets", Type: TypeStatsCounter, Access: ReadOnly, SinceVersion: "1.0", Description: "Packets received from this peer."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.TXPackets", Type: TypeStatsCounter, Access: ReadOnly, SinceVersion: "1.0", Description: "Packets transmitted to this peer."},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.ExpectedThroughput", Type: TypeUnsignedLong, Access: ReadOnly, SinceVersion: "1.0", Description: "Expected peer throughput in bits per second.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "IEEE80211s.{i}.Peer.{i}.LastSeen", Type: TypeDateTime, Access: ReadOnly, SinceVersion: "1.0", Description: "Timestamp when this peer was last observed."},
}

var WUSPMeshTelemetryBATMANAdvParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Alias", Type: TypeAlias, Access: ReadWrite, SinceVersion: "1.0", Description: "USP non-functional unique key for this batman-adv row.", Limits: Limits{MinLength: 1, MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Enable", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "Enables the OpenWrt batman-adv interface when the agent supports configuration writes."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Status", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "batman-adv interface runtime status.", Limits: Limits{Enums: []string{"Up", "Down", "LowerLayerDown", "Degraded", "Error", "Unknown"}}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.ProtocolReference", Type: TypePathRef, Access: ReadOnly, SinceVersion: "1.0", Description: "Reference to Device.WUSP_MeshTelemetry.Protocol.{i}. for batman-adv."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.InterfaceName", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Linux batman-adv soft interface name.", Limits: Limits{MaxLength: 32}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.RoutingAlgorithm", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt routing_algo option.", Limits: Limits{Enums: []string{"BATMAN_IV", "BATMAN_V"}}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.AggregatedOGMs", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt aggregated_ogms option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Fragmentation", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt fragmentation option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.GatewayMode", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt gw_mode option.", Limits: Limits{Enums: []string{"off", "client", "server"}}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.GatewayBandwidth", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt gw_bandwidth option.", Limits: Limits{MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.GatewaySelectionClass", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt gw_sel_class option.", Limits: Limits{Min: iptr(0), Max: iptr(256)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.OrigInterval", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt orig_interval option in milliseconds.", Limits: Limits{Min: iptr(1)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.BridgeLoopAvoidance", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt bridge_loop_avoidance option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.DistributedARPTable", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt distributed_arp_table option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.MulticastMode", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt multicast_mode option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.MulticastFanout", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt multicast_fanout option.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.HopPenalty", Type: TypeUnsignedInt, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt hop_penalty option.", Limits: Limits{Min: iptr(0), Max: iptr(255)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.APIsolation", Type: TypeBoolean, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt ap_isolation option."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.IsolationMark", Type: TypeString, Access: ReadWrite, SinceVersion: "1.0", Description: "OpenWrt isolation_mark value/mask option.", Limits: Limits{Pattern: "^0x[0-9A-Fa-f]{1,8}/0x[0-9A-Fa-f]{1,8}$"}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.OriginatorNumberOfEntries", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Number of batman-adv originator rows.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.NeighborNumberOfEntries", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Number of batman-adv neighbor rows.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTableNumberOfEntries", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Number of batman-adv translation-table rows.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.GatewayNumberOfEntries", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Number of batman-adv gateway rows.", Limits: Limits{Min: iptr(0)}},
}

var WUSPMeshTelemetryBATMANAdvOriginatorParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.OriginatorAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Originator MAC address."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.NextHopAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Selected next-hop MAC address for this originator."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.InterfaceName", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Incoming batman-adv hard interface name.", Limits: Limits{MaxLength: 32}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.TQ", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "BATMAN-IV transmission quality metric.", Limits: Limits{Min: iptr(0), Max: iptr(255)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.ThroughputEstimate", Type: TypeUnsignedLong, Access: ReadOnly, SinceVersion: "1.0", Description: "BATMAN-V throughput estimate in bits per second.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Originator.{i}.LastSeen", Type: TypeDateTime, Access: ReadOnly, SinceVersion: "1.0", Description: "Timestamp when this originator was last observed."},
}

var WUSPMeshTelemetryBATMANAdvNeighborParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.NeighborAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Neighbor MAC address."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.InterfaceName", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "Hard interface where this neighbor is reachable.", Limits: Limits{MaxLength: 32}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.TQ", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Neighbor transmission quality metric.", Limits: Limits{Min: iptr(0), Max: iptr(255)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.ThroughputEstimate", Type: TypeUnsignedLong, Access: ReadOnly, SinceVersion: "1.0", Description: "Neighbor throughput estimate in bits per second.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Neighbor.{i}.LastSeen", Type: TypeDateTime, Access: ReadOnly, SinceVersion: "1.0", Description: "Timestamp when this neighbor was last observed."},
}

var WUSPMeshTelemetryBATMANAdvTranslationTableParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.MACAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Client MAC address in the batman-adv translation table."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.VLANID", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "VLAN ID for this translation-table row.", Limits: Limits{Min: iptr(0), Max: iptr(4094)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.OriginatorAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Originator advertising this client."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.Flags", Type: TypeString, Access: ReadOnly, SinceVersion: "1.0", Description: "batman-adv translation-table flags.", Limits: Limits{MaxLength: 64}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.IsLocal", Type: TypeBoolean, Access: ReadOnly, SinceVersion: "1.0", Description: "Whether this translation-table entry is local."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.TranslationTable.{i}.LastSeen", Type: TypeDateTime, Access: ReadOnly, SinceVersion: "1.0", Description: "Timestamp when this translation-table row was last observed."},
}

var WUSPMeshTelemetryBATMANAdvGatewayParams = []Param{
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.GatewayAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Gateway originator MAC address."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.Selected", Type: TypeBoolean, Access: ReadOnly, SinceVersion: "1.0", Description: "Whether this gateway is currently selected."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.TQ", Type: TypeUnsignedInt, Access: ReadOnly, SinceVersion: "1.0", Description: "Gateway path transmission quality metric.", Limits: Limits{Min: iptr(0), Max: iptr(255)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.BandwidthDown", Type: TypeUnsignedLong, Access: ReadOnly, SinceVersion: "1.0", Description: "Advertised gateway download bandwidth in bits per second.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.BandwidthUp", Type: TypeUnsignedLong, Access: ReadOnly, SinceVersion: "1.0", Description: "Advertised gateway upload bandwidth in bits per second.", Limits: Limits{Min: iptr(0)}},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.NextHopAddress", Type: TypeMACAddress, Access: ReadOnly, SinceVersion: "1.0", Description: "Selected next-hop MAC address toward this gateway."},
	{Path: WUSPMeshTelemetryPrefix + "BATMANAdv.{i}.Gateway.{i}.LastSeen", Type: TypeDateTime, Access: ReadOnly, SinceVersion: "1.0", Description: "Timestamp when this gateway row was last observed."},
}

var AllWUSPMeshTelemetryParams = concat(
	WUSPMeshTelemetryRootParams,
	WUSPMeshTelemetryNodeParams,
	WUSPMeshTelemetryLinkParams,
	WUSPMeshTelemetryRouteParams,
	WUSPMeshTelemetryProtocolParams,
	WUSPMeshTelemetryIEEE80211sParams,
	WUSPMeshTelemetryIEEE80211sPeerParams,
	WUSPMeshTelemetryBATMANAdvParams,
	WUSPMeshTelemetryBATMANAdvOriginatorParams,
	WUSPMeshTelemetryBATMANAdvNeighborParams,
	WUSPMeshTelemetryBATMANAdvTranslationTableParams,
	WUSPMeshTelemetryBATMANAdvGatewayParams,
)
