services:
  client1:
    privileged: true  
    build:
      context: ../../
      dockerfile: e2e/docker-compose/Dockerfile.dev
    container_name: wantasticd-client1
    command: [ "air", "-c", ".air-openwrt.toml" ]
    volumes:
      - ../../:/app
      - ./configs/client1.conf:/etc/wantasticd/wg.conf:ro
    environment:
      - LOG_LEVEL=debug
    extra_hosts:
      - "wg.wantastic.local:host-gateway"
    networks:
      wantastic-e2e:
        ipv4_address: 172.25.0.11
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  client2:
    privileged: true
    build:
      context: ../../
      dockerfile: e2e/docker-compose/Dockerfile.dev
    container_name: wantasticd-client2
    command: [ "air", "-c", ".air-openwrt.toml" ]
    volumes:
      - ../../:/app
      - ./configs/client2.conf:/etc/wantasticd/wg.conf:ro
    environment:
      - LOG_LEVEL=debug
    extra_hosts:
      - "wg.wantastic.local:host-gateway"
    networks:
      wantastic-e2e:
        ipv4_address: 172.25.0.12
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  client3:
    privileged: true
    build:
      context: ../../
      dockerfile: e2e/docker-compose/Dockerfile.dev
    container_name: wantasticd-client3
    command: [ "air", "-c", ".air-openwrt.toml" ]
    volumes:
      - ../../:/app
      - ./configs/client3.conf:/etc/wantasticd/wg.conf:ro
    environment:
      - LOG_LEVEL=debug
    extra_hosts:
      - "wg.wantastic.local:host-gateway"
    networks:
      wantastic-e2e:
        ipv4_address: 172.25.0.13
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  wantastic-e2e:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
