[Interface]
PrivateKey = SAlPC0DMT9qPqL7I3fFUvkaA0SMUsGye9GAJrZ3IsGc=
Address = 10.0.0.5/32

[Peer]
PublicKey = CihM+l93agpGcGwe+lSkLcJ5nFy8stdTENvEOcDMAV8=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
