[Interface]
PrivateKey = 0JR/vM4EJFyiQytL8KuUsAkLvwtlc5Jueo+KX66HJG4=
Address = 10.0.0.3/32

[Peer]
PublicKey = z7lx3lUh/qFRmsNGlDaVnesZNcBIwMcIWIBOtH17yyk=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
