[Interface]
PrivateKey = eKXmUsd6TCb/anDlf/N5O4BOw4Qc+tw3iSAYZl3E02E=
Address = 10.0.0.2/32

[Peer]
PublicKey = tKB1m94+XsYmTf+8jmLSXze/BL+0clxhIfp0q1VRxUg=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
