[Interface]
PrivateKey = 8BrIHGlW98neRdRgHXkp6CE/r7ZbCHz1j4gkX+kRaW0=
Address = 10.0.0.5/32

[Peer]
PublicKey = nCwnKpc6y7/Efkhjlw7Pk+b1t8bBxhND7wpa+O4DBHE=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
