[Interface]
PrivateKey = qHbPDh0viyDRpgGAempQs7gTjvHIwAA5LNHZDFJiamA=
Address = 10.0.0.2/32

[Peer]
PublicKey = pktzQ6kuT/zkX2WBA0zKzboZh89b/Wsq0SHCJx8ktWM=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
