[Interface]
PrivateKey = mACNdf9+/+6JPNDFewMCe9ORyHYd6FatL9Q9Q0qxHVc=
Address = 10.0.0.3/32

[Peer]
PublicKey = CihM+l93agpGcGwe+lSkLcJ5nFy8stdTENvEOcDMAV8=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
