[Interface]
PrivateKey = iKw1QlZnoTIhTFU41/bQWCiFo4b6ygcjxicV2tiJK00=
Address = 10.0.0.2/32

[Peer]
PublicKey = CihM+l93agpGcGwe+lSkLcJ5nFy8stdTENvEOcDMAV8=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
