[Interface]
PrivateKey = yKS93Kqk3iiqzHA2Uke8IaSnpD5d2CsTOey74pjc2Fo=
Address = 10.0.0.4/32

[Peer]
PublicKey = tKB1m94+XsYmTf+8jmLSXze/BL+0clxhIfp0q1VRxUg=
Endpoint = wg.wantastic.local:51820
AllowedIPs = 10.0.0.0/27
PersistentKeepalive = 25
