// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseConsoleWebView():Promise<void>;

export function FormatBytes(arg1:number):Promise<string>;

export function GetAccount():Promise<main.AccountInfo>;

export function GetIPCPort():Promise<string>;

export function GetPortalHost():Promise<string>;

export function GetStatus():Promise<main.StatusData>;

export function GetVersion():Promise<string>;

export function IsConfigured():Promise<boolean>;

export function IsDaemonRunning():Promise<boolean>;

export function Logout():Promise<void>;

export function OpenConsole():Promise<void>;

export function OpenConsoleWebView():Promise<void>;

export function PubKeyShort(arg1:string):Promise<string>;

export function SetExitNode(arg1:string):Promise<void>;

export function StartLogin():Promise<void>;

export function ToggleExitNode():Promise<void>;

export function ToggleVPN():Promise<void>;

export function TruncateKey(arg1:string):Promise<string>;

export function WindowHide():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowStartDrag():Promise<void>;
