// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConsoleWebView() {
  return window['go']['main']['App']['CloseConsoleWebView']();
}

export function FormatBytes(arg1) {
  return window['go']['main']['App']['FormatBytes'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetIPCPort() {
  return window['go']['main']['App']['GetIPCPort']();
}

export function GetPortalHost() {
  return window['go']['main']['App']['GetPortalHost']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function IsDaemonRunning() {
  return window['go']['main']['App']['IsDaemonRunning']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenConsole() {
  return window['go']['main']['App']['OpenConsole']();
}

export function OpenConsoleWebView() {
  return window['go']['main']['App']['OpenConsoleWebView']();
}

export function PubKeyShort(arg1) {
  return window['go']['main']['App']['PubKeyShort'](arg1);
}

export function SetExitNode(arg1) {
  return window['go']['main']['App']['SetExitNode'](arg1);
}

export function StartLogin() {
  return window['go']['main']['App']['StartLogin']();
}

export function ToggleExitNode() {
  return window['go']['main']['App']['ToggleExitNode']();
}

export function ToggleVPN() {
  return window['go']['main']['App']['ToggleVPN']();
}

export function TruncateKey(arg1) {
  return window['go']['main']['App']['TruncateKey'](arg1);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowStartDrag() {
  return window['go']['main']['App']['WindowStartDrag']();
}
